### ISSUE TITLE
help-me

### ISSUE THREAD

**Issue by heraldo1980** [NerduMiner/bfntoolkit#1]
Friend could you help me?

I would like to know how to use the correct wimgt path and sentaxy to convert the PNG to BTI, I know this kind of help is annoying, but just this once if you can help me I would be very grateful.

**Comment by NerduMiner** [comment]
On Windows, I prefer to use a batch script with wimgt to batch convert all images in a bfn's directory.
I installed wimgt to my system so I can just invoke it by name alone. if you have a local exe you will have to replace the call to wimgt with the path to the executable.
```
for %%a in ("./*.png") do (
wimgt encode %%a -d %%~pa%%~na.bti -x BTI.IA4 --n-mm=0
)
```
EDIT: You can download this batch script directly from the repository, since I included it for convenience.

**Comment by heraldo1980** [comment]
Oh thank you very much. 😍
