### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by TeMouRen** [NerduMiner/bfntoolkit#3]
How to edit the unpacked bfn file, although I know that Wiimms can be edited, but I am a freshman, I don't understand at all, I know this is stupid, but can you help me

**Comment by NerduMiner** [comment]
Wiimms is only needed for when you are satisfied with your edits and need to convert the images back into .bti files. You can use any other image editor to work on the exported image files. As for the BFN information, that is all in the exported data.json. You can find a link to a page detailing the format on the Readme. I can't really help with setting up the required tools since its highly dependent on your computer setup, so I hope what I've noted down here is useful.

**Comment by TeMouRen** [comment]
Thank you.I thought Wiimms could be edited directly.
